### ISSUE TITLE
Numbers get grouped by 4 when length % 3 is 1

### ISSUE THREAD

**Issue by BehroozAmoozad** [sh1boot/digitgrouper#1]
The first 4 digits of any 4 7 10 13 digit number are grouped as 4 instead of 3.
![Screenshot From 2024-10-29 22-55-19](https://github.com/user-attachments/assets/d1aa716f-a0d4-4104-864d-fe8d5f6ae27f)

**Comment by sh1boot** [comment]
Yeah, my original intent was a strict "no orphan" policy, so that I would never leave a single digit standing out on its own, because I though that looked funny. 

But actually groups of four seem to look worse.  I've been meaning to fix it for a while.

**Comment by BehroozAmoozad** [comment]
I can handle the single and two digit cases programmatically and disable the `dgco` where I'm using this.   

The `Gtk` UI toolkit `Entries` don't support any kind of digit grouping.  If this is fixed, it can make digitgrouper the best option for a lot of applications that need digit grouping for arbitrary fonts.

**Comment by BehroozAmoozad** [comment]
Does reducing `> 6` to `> 3` require writing a `capture_2digit` criteria?    
I've never worked on fonts before. Am I understanding this correctly?

**Comment by sh1boot** [comment]
No, it's just that it's against typesetting convention to add a thousand separator to four-digit numbers, and five and six don't produce an orphan digit.  Seven digits is the first case where there's one digit isolated out on its own.

**Comment by BehroozAmoozad** [comment]
7 and 10 working now makes this absolutely usable for what I'm doing. It'd be awesome if it could be added later as a toggle or another forced font face later on.  
 
Thank You for putting in the time to fix this. Much appreciated.
